pipeline {
    agent any

    stages {
        stage('Compile Code') {
            steps {
                sh "./mvnw clean compile -e"
            }
        }
        stage('Test Code') {
            steps {
                sh "./mvnw clean test -e"
            }
        }
        stage('Jar Code') {
            steps {
                sh "./mvnw clean package -e"
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('LocalSonar') {
                    sh './mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar'
                }
            }
        }
        stage('Run Jar') {
            steps {
                sh '''
                ./mvnw spring-boot:run > server.log 2>&1&
                while [ $(cat server.log | grep -c "Started DevOpsUsach2020Application") -eq 0 ]
                do
                    sleep 1
                done
                '''
            }
        }
        stage('Testing Application') {
            steps {
                sh "curl -X GET 'http://localhost:8081/rest/mscovid/test?msg=testing'"
            }
        }
    }
}
